import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { NextAuthProvider } from "./Providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
    <head>
     
      <link rel="icon" href="/images/favicon.ico" />
    </head>
    <body className="antialiased">
      <NextAuthProvider>
        <div className="relative w-full flex items-center justify-center">
          <Navbar />
        </div>
        {children}
      </NextAuthProvider>
    </body>
  </html>
  );
}
